# Generated by Django 5.1.6 on 2025-03-18 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printease', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrintEaseSignModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='PrintEaseLoginModel',
        ),
    ]
