# Generated by Django 5.1.6 on 2025-04-12 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printease', '0002_order_quality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='quality',
        ),
    ]
