# Generated by Django 5.1.6 on 2025-04-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printease', '0002_alter_order_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filesupload',
            name='uploaded_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
