# Generated by Django 5.1.6 on 2025-04-12 03:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printease', '0003_remove_order_quality'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='quality',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
