# Generated by Django 5.1.6 on 2025-04-12 11:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printease', '0005_remove_order_quality'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='product_type',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
