# Generated by Django 5.1.6 on 2025-04-12 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printease', '0006_order_product_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderBillModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(max_length=600)),
                ('company_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=1000)),
                ('paper_type', models.CharField(max_length=100)),
                ('paper_size', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('number_of_book', models.IntegerField(default=1)),
                ('page_per_book', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_bill_model', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
