# Generated by Django 5.1.6 on 2025-04-12 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printease', '0007_orderbillmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderbillmodel',
            name='number_of_book',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='orderbillmodel',
            name='page_per_book',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='orderbillmodel',
            name='quantity',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
    ]
