# Generated by Django 5.1.6 on 2025-04-12 14:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printease', '0008_alter_orderbillmodel_number_of_book_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderbillmodel',
            name='file',
            field=models.FileField(default=django.utils.timezone.now, upload_to='uploads/'),
            preserve_default=False,
        ),
    ]
