# Generated by Django 5.1.6 on 2025-04-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printease', '0009_orderbillmodel_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderbillmodel',
            name='file',
        ),
        migrations.AddField(
            model_name='orderbillmodel',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='billbook_logos/'),
        ),
    ]
