# Generated by Django 5.1.6 on 2025-04-12 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printease', '0010_remove_orderbillmodel_file_orderbillmodel_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderLetterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_type', models.CharField(max_length=600)),
                ('company_name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=1000)),
                ('paper_type', models.CharField(max_length=100)),
                ('paper_size', models.CharField(max_length=50)),
                ('quantity', models.PositiveIntegerField(default=1, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='letterhead_logos/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_letter_model', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
