# Generated by Django 5.1.6 on 2025-04-12 20:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printease', '0011_orderlettermodel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlettermodel',
            name='order_type',
            field=models.CharField(default='Letterhead', max_length=600),
        ),
        migrations.AlterField(
            model_name='orderlettermodel',
            name='paper_size',
            field=models.CharField(choices=[('A4', 'A4 (210 × 297 mm)'), ('Letter', 'Letter (8.5 × 11 inches)')], max_length=50),
        ),
        migrations.AlterField(
            model_name='orderlettermodel',
            name='paper_type',
            field=models.CharField(choices=[('Standard', 'Standard'), ('Premium', 'Premium')], max_length=100),
        ),
        migrations.AlterField(
            model_name='orderlettermodel',
            name='quantity',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='orderlettermodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
