# Generated by Django 5.1.6 on 2025-04-21 07:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printease', '0014_orderbillmodel_order_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlettermodel',
            name='order_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
